Install Azure CLI
CircleCI-Public/cimg-deploy pull request #2
Opened 2022-05-05 17:10 UTC by jschwanz

The steps to install Azure CLI were modeled after the [MS docs](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt). I also introduced some extra commands to existing steps to perform some cache cleaning for image minimization purposes.

2022-05-09 13:50 UTC, felicianotech requested changes
Hi,

Thanks for the PR. For Convenience Images, we need to make changes to the `Dockerfile.template` file. This file then eventually gets parsed and turned into actual releases. Would you be able to adjust this PR so that file is modified instead?

2022-05-09 13:55 UTC, jschwanz commented
Can do.

2022-05-23 16:20 UTC, felicianotech approved these changes

2022-05-23 16:20 UTC, merged

2022-05-23 16:25 UTC, felicianotech commented
Thank you